// Auto-generated file

import { IMsg, IMessageSet } from '@iffycan/i18n'
export interface IMessages extends IMessageSet {
  "\n        Though filling out this form is preferrable, you can also email bugs@budgetwithbuckets.com\n      ": IMsg<string>;
  "(Drop files or click)": IMsg<string>;
  "(If you want a response)": IMsg<string>;
  "(optional)": IMsg<string>;
  "/mo": IMsg<string>;
  "A sync is already in progress": IMsg<string>;
  "About Buckets": IMsg<string>;
  "Account": IMsg<string>;
  "Account Transactions": IMsg<string>;
  "Account and transactions deleted": IMsg<string>;
  "Account closed": IMsg<string>;
  "Account created: ": IMsg<string>;
  "Account deleted completely": IMsg<string>;
  "Account name": IMsg<string>;
  "Accounts": IMsg<string>;
  "Actions": IMsg<string>;
  "Activity": IMsg<string>;
  "Actual Size": IMsg<string>;
  "Amazon.com Reconciliation": IMsg<string>;
  "Amount": IMsg<string>;
  "Amount of money over-allocated in buckets.": IMsg<string>;
  "Analysis": IMsg<string>;
  "Animation": IMsg<string>;
  "Any other monthly bills you have?": IMsg<string>;
  "Attached files are too large.": IMsg<string>;
  "Average": IMsg<string>;
  "Avg:": IMsg<string>;
  "Babysitting": IMsg<string>;
  "Balance": IMsg<string>;
  "Balance:": IMsg<string>;
  "Beta Updates": IMsg<string>;
  "Birthdays": IMsg<string>;
  "Break Import Links": IMsg<string>;
  "Bring All to Front": IMsg<string>;
  "Bucket": IMsg<string>;
  "Bucket Transactions": IMsg<string>;
  "Bucket deleted completely": IMsg<string>;
  "Bucket type:": IMsg<string>;
  "Buckets": IMsg<string>;
  "Buckets Budget Filename": IMsg<string>;
  "Buckets Guide": IMsg<string>;
  "Buckets License": IMsg<string>;
  "Budget": IMsg<string>;
  "Budget Settings": IMsg<string>;
  "Budget password:": IMsg<string>;
  "Budgeted": IMsg<string>;
  "CSV Account": IMsg<string>;
  "CSV Fields": IMsg<string>;
  "Cable TV": IMsg<string>;
  "Cancel": IMsg<string>;
  "Cancel sync": IMsg<string>;
  "Car Insurance": IMsg<string>;
  "Car Maintenance": IMsg<string>;
  "Car Payment": IMsg<string>;
  "Categorization": IMsg<string>;
  "Categorize": IMsg<string>;
  "Category": IMsg<string>;
  "Charity": IMsg<string>;
  "Chat with Matt": IMsg<string>;
  "Chat...": IMsg<string>;
  "Check For Updates...": IMsg<string>;
  "Check for Updates": IMsg<string>;
  "Checking for updates...": IMsg<string>;
  "Cleared": IMsg<string>;
  "Click the \"Set mapping\" to continue.": IMsg<string>;
  "Close Account": IMsg<string>;
  "Close Window": IMsg<string>;
  "Close account": IMsg<string>;
  "Closed": IMsg<string>;
  "Clothing": IMsg<string>;
  "Confirm password:": IMsg<string>;
  "Connect": IMsg<string>;
  "Connect to bank": IMsg<string>;
  "Connecting...": IMsg<string>;
  "Connection saved!": IMsg<string>;
  "Copy": IMsg<string>;
  "Create Account": IMsg<string>;
  "Create Backup": IMsg<string>;
  "Create Backup and Start Over": IMsg<string>;
  "Create Macro": IMsg<string>;
  "Create Template": IMsg<string>;
  "Create Transaction": IMsg<string>;
  "Create budget password:": IMsg<string>;
  "Create macro": IMsg<string>;
  "Create new account": IMsg<string>;
  "Currency symbol": IMsg<string>;
  "Cut": IMsg<string>;
  "Date Posted": IMsg<string>;
  "Debt": IMsg<string>;
  "Delete": IMsg<string>;
  "Delete Account": IMsg<string>;
  "Delete Connection": IMsg<string>;
  "Delete Group": IMsg<string>;
  "Delete Macro": IMsg<string>;
  "Delete Transactions": IMsg<string>;
  "Delete all": IMsg<string>;
  "Description": IMsg<string>;
  "Diapers": IMsg<string>;
  "Disable Macro": IMsg<string>;
  "Done": IMsg<string>;
  "Download": IMsg<string>;
  "Download Update": IMsg<string>;
  "Downloading update...": IMsg<string>;
  "Duplicate Window": IMsg<string>;
  "EXPERIMENTAL Buckets Macro Maker": IMsg<string>;
  "Eating out": IMsg<string>;
  "Edit": IMsg<string>;
  "Electricity": IMsg<string>;
  "Enable Macro": IMsg<string>;
  "Enable to get new versions of Buckets before everyone else.  There might be more bugs :)": IMsg<string>;
  "Ending Balance": IMsg<string>;
  "Ending amount:": IMsg<string>;
  "Enter Buckets License": IMsg<string>;
  "Enter License...": IMsg<string>;
  "Error": IMsg<string>;
  "Error fetching data": IMsg<string>;
  "Error importing": IMsg<string>;
  "Error parsing response": IMsg<string>;
  "Error running recording": IMsg<string>;
  "Error running sync": IMsg<string>;
  "Expenses": IMsg<string>;
  "Export": IMsg<string>;
  "File": IMsg<string>;
  "File does not exist:": IMsg<string>;
  "File saved: ": IMsg<string>;
  "File type not recognized.": IMsg<string>;
  "Find Next": IMsg<string>;
  "Find Previous": IMsg<string>;
  "Find...": IMsg<string>;
  "Finish import": IMsg<string>;
  "For Date Posted, you must also choose the date format.": IMsg<string>;
  "Force Reload": IMsg<string>;
  "From": IMsg<string>;
  "Fuel": IMsg<string>;
  "Gain/Loss": IMsg<string>;
  "Getting Started...": IMsg<string>;
  "Goal completion:": IMsg<string>;
  "Goal:": IMsg<string>;
  "Goal: 0": IMsg<string>;
  "Groceries": IMsg<string>;
  "Header row": IMsg<string>;
  "Health Insurance": IMsg<string>;
  "Hello!  Thanks for trying out Buckets.": IMsg<string>;
  "Help": IMsg<string>;
  "Hide Buckets": IMsg<string>;
  "Hide Others": IMsg<string>;
  "Holidays": IMsg<string>;
  "Household goods": IMsg<string>;
  "I'm exporting data so that I can ": IMsg<string>;
  "ID": IMsg<string>;
  "Identify the data each column contains using the drop downs below.": IMsg<string>;
  "If Net is 0, the bucket transactions will be marked as transfers rather than as income or expenses.": IMsg<string>;
  "If multiple columns are selected for Amount, the first non-zero value will be used.  This is helpful if the CSV contains separate Credit and Debit columns.": IMsg<string>;
  "Import": IMsg<string>;
  "Import From YNAB4...": IMsg<string>;
  "Import Transactions...": IMsg<string>;
  "Import all Amazon Reports": IMsg<string>;
  "Import an Amazon Items report to see order details.": IMsg<string>;
  "Import file": IMsg<string>;
  "Import from YNAB4": IMsg<string>;
  "Import links broken": IMsg<string>;
  "In": IMsg<string>;
  "In/Out": IMsg<string>;
  "Include log file": IMsg<string>;
  "Income": IMsg<string>;
  "Install and Relaunch Buckets": IMsg<string>;
  "Internet": IMsg<string>;
  "Invalid": IMsg<string>;
  "Invalid SimpleFIN Token": IMsg<string>;
  "Invalid categorization.  Categories not set.": IMsg<string>;
  "Invalid license": IMsg<string>;
  "It says:": IMsg<string>;
  "It should say:": IMsg<string>;
  "Item": IMsg<string>;
  "Keep account transactions": IMsg<string>;
  "Keep accounts": IMsg<string>;
  "Keep bucket transactions": IMsg<string>;
  "Keep buckets": IMsg<string>;
  "Kick Bucket": IMsg<string>;
  "Kick the bucket": IMsg<string>;
  "Kicked": IMsg<string>;
  "Language": IMsg<string>;
  "Language default": IMsg<string>;
  "Last used": IMsg<string>;
  "Later": IMsg<string>;
  "Learn More": IMsg<string>;
  "Life Insurance": IMsg<string>;
  "Link Account": IMsg<string>;
  "Macros": IMsg<string>;
  "Make Account Off Budget": IMsg<string>;
  "Make Account On Budget": IMsg<string>;
  "Make Transfer": IMsg<string>;
  "Make it rain!": IMsg<string>;
  "Make it so": IMsg<string>;
  "Mark Cleared": IMsg<string>;
  "Mark Not Cleared": IMsg<string>;
  "Medical": IMsg<string>;
  "Memo": IMsg<string>;
  "Minimize": IMsg<string>;
  "Month to Month": IMsg<string>;
  "Monthly deposit:": IMsg<string>;
  "Months": IMsg<string>;
  "Move Bucket": IMsg<string>;
  "Move Group": IMsg<string>;
  "Name": IMsg<string>;
  "Natural gas/propane/oil": IMsg<string>;
  "Need ideas for getting started?": IMsg<string>;
  "Needs": IMsg<string>;
  "Negate": IMsg<string>;
  "Negative": IMsg<string>;
  "Net": IMsg<string>;
  "Net Transfers": IMsg<string>;
  "New Bucket": IMsg<string>;
  "New Budget...": IMsg<string>;
  "New Group": IMsg<string>;
  "New account": IMsg<string>;
  "New bucket": IMsg<string>;
  "New car": IMsg<string>;
  "New computer": IMsg<string>;
  "New phone": IMsg<string>;
  "New roof": IMsg<string>;
  "No file chosen": IMsg<string>;
  "No matches found": IMsg<string>;
  "Not Transfer": IMsg<string>;
  "Not yet cleared": IMsg<string>;
  "Note": IMsg<string>;
  "Nothing found matching:": IMsg<string>;
  "Number format": IMsg<string>;
  "OK": IMsg<string>;
  "Off Budget Accounts": IMsg<string>;
  "Off budget": IMsg<string>;
  "On": IMsg<string>;
  "Only select a column for Unique ID if you are sure it contains bank-assigned, unique transaction IDs.  Most CSVs will not have this field.": IMsg<string>;
  "Open Buckets Budget": IMsg<string>;
  "Open Budget...": IMsg<string>;
  "Open Recent...": IMsg<string>;
  "Open Transaction File": IMsg<string>;
  "Open YNAB4 File": IMsg<string>;
  "Optional message:": IMsg<string>;
  "Optionally request a Amazon Refunds report": IMsg<string>;
  "Or click to download the new version manually.": IMsg<string>;
  "Out": IMsg<string>;
  "Passwords did not match": IMsg<string>;
  "Paste": IMsg<string>;
  "Paste and Match Style": IMsg<string>;
  "Paused": IMsg<string>;
  "Permanently delete account": IMsg<string>;
  "Personal Loan Payment": IMsg<string>;
  "Phone": IMsg<string>;
  "Playing": IMsg<string>;
  "Possible Duplicates": IMsg<string>;
  "Posted": IMsg<string>;
  "Preferences": IMsg<string>;
  "Preferences...": IMsg<string>;
  "Preparation": IMsg<string>;
  "Prompt": IMsg<string>;
  "Provide a name for the new account.": IMsg<string>;
  "Purchase": IMsg<string>;
  "Purchase Full Version...": IMsg<string>;
  "Quit Buckets": IMsg<string>;
  "Rain": IMsg<string>;
  "Rain left": IMsg<string>;
  "Rainfall this month:": IMsg<string>;
  "Recently used": IMsg<string>;
  "Record change as transaction": IMsg<string>;
  "Recording": IMsg<string>;
  "Recurring Expenses": IMsg<string>;
  "Redo": IMsg<string>;
  "Reload": IMsg<string>;
  "Remove Categorization": IMsg<string>;
  "Rent/Mortgage": IMsg<string>;
  "Reopen": IMsg<string>;
  "Reopen Account": IMsg<string>;
  "Report Bug": IMsg<string>;
  "Report Bug...": IMsg<string>;
  "Report Translation Error...": IMsg<string>;
  "Request an Amazon Items report": IMsg<string>;
  "Request an Amazon Orders report": IMsg<string>;
  "Required deposit:": IMsg<string>;
  "Restart Buckets": IMsg<string>;
  "Restart Buckets for changes to take effect.": IMsg<string>;
  "Save": IMsg<string>;
  "Screenshots:": IMsg<string>;
  "Search": IMsg<string>;
  "Search:": IMsg<string>;
  "Searching...": IMsg<string>;
  "Select All": IMsg<string>;
  "Select the account these transactions belong to.": IMsg<string>;
  "Self debt": IMsg<string>;
  "Send Report": IMsg<string>;
  "Services": IMsg<string>;
  "Set mapping": IMsg<string>;
  "Settings": IMsg<string>;
  "Show All": IMsg<string>;
  "Show Log Files...": IMsg<string>;
  "Show uncategorized": IMsg<string>;
  "Sign": IMsg<string>;
  "SimpleFIN Connections": IMsg<string>;
  "Skip This Version": IMsg<string>;
  "Speech": IMsg<string>;
  "Spending Money": IMsg<string>;
  "Start Over": IMsg<string>;
  "Start Speaking": IMsg<string>;
  "Start with a template": IMsg<string>;
  "Step took too long": IMsg<string>;
  "Stop Speaking": IMsg<string>;
  "Student Loan Payment": IMsg<string>;
  "Submit": IMsg<string>;
  "Submit feedback": IMsg<string>;
  "Success!": IMsg<string>;
  "Successfully imported Amazon Items report": IMsg<string>;
  "Successfully imported Amazon Orders report": IMsg<string>;
  "Successfully imported Amazon Refunds report": IMsg<string>;
  "Sync": IMsg<string>;
  "Sync complete": IMsg<string>;
  "Sync failed": IMsg<string>;
  "Sync has not yet been set up.": IMsg<string>;
  "Synced balance": IMsg<string>;
  "Syncing...": IMsg<string>;
  "System default": IMsg<string>;
  "Target date:": IMsg<string>;
  "Test Toast": IMsg<string>;
  "Thank you for the feedback!": IMsg<string>;
  "There has been an error.": IMsg<string>;
  "There was an error.  Maybe try again?": IMsg<string>;
  "This is a special group for all the buckets without a group.": IMsg<string>;
  "This tool will delete data to make it easy to start over with your budget.": IMsg<string>;
  "Timezone": IMsg<string>;
  "To": IMsg<string>;
  "Toggle Developer Tools": IMsg<string>;
  "Toggle Full Screen": IMsg<string>;
  "Tools": IMsg<string>;
  "Tot:": IMsg<string>;
  "Total amount your buckets expect each month.": IMsg<string>;
  "Transaction": IMsg<string>;
  "Transactions": IMsg<string>;
  "Transactions to review": IMsg<string>;
  "Transfer": IMsg<string>;
  "Trial Version": IMsg<string>;
  "Tuition": IMsg<string>;
  "Un-kick": IMsg<string>;
  "Un-kick Bucket": IMsg<string>;
  "Unable to claim access token": IMsg<string>;
  "Unable to open the file:": IMsg<string>;
  "Undo": IMsg<string>;
  "Unexpected sync error": IMsg<string>;
  "Unique ID": IMsg<string>;
  "Unknown account: ": IMsg<string>;
  "Unknown category": IMsg<string>;
  "Unlinked Accounts": IMsg<string>;
  "Unregistered Version": IMsg<string>;
  "Update Account Balance": IMsg<string>;
  "Update Account Name": IMsg<string>;
  "Update Available": IMsg<string>;
  "Update Bucket Name": IMsg<string>;
  "Update Bucket Type": IMsg<string>;
  "Update Color": IMsg<string>;
  "Update Goal": IMsg<string>;
  "Update Group Name": IMsg<string>;
  "Update Macro Name": IMsg<string>;
  "Update Monthly Deposit": IMsg<string>;
  "Update Name": IMsg<string>;
  "Update Note": IMsg<string>;
  "Update Target Date": IMsg<string>;
  "Update Transaction": IMsg<string>;
  "Update account balance": IMsg<string>;
  "Update balance": IMsg<string>;
  "Update balance without a transaction": IMsg<string>;
  "Update downloaded.": IMsg<string>;
  "Used in future": IMsg<string>;
  "Vacation ": IMsg<string>;
  "View": IMsg<string>;
  "Want": IMsg<string>;
  "Wants": IMsg<string>;
  "Warning: Doing this will use rain you don't have and could steal rain from future months (if available).": IMsg<string>;
  "Water": IMsg<string>;
  "When \"On\" this macro will be run during a normal sync.": IMsg<string>;
  "Window": IMsg<string>;
  "Year to Year": IMsg<string>;
  "Year's Supply": IMsg<string>;
  "Years": IMsg<string>;
  "You are running the latest version!": IMsg<string>;
  "You don't have any recurring expense buckets yet.": IMsg<string>;
  "You have no closed accounts.": IMsg<string>;
  "You haven't kicked the bucket yet...": IMsg<string>;
  "You must backup to a different file.": IMsg<string>;
  "You must have at least one column each set to Amount, Memo and Date Posted.": IMsg<string>;
  "Your email address:": IMsg<string>;
  "Zoom": IMsg<string>;
  "Zoom In": IMsg<string>;
  "Zoom Out": IMsg<string>;
  "account-bal-diff-1": IMsg<string>;
  "account-bal-diff-fix-1": IMsg<string>;
  "account-bal-diff-fix-2": IMsg<string>;
  "accounts.balance_mismatch_msg": IMsg<string>;
  "accounts.name_placeholder": IMsg<string>;
  "action.New bucket": IMsg<string>;
  "action.New group": IMsg<string>;
  "action.ignore": IMsg<string>;
  "action.link-account": IMsg<string>;
  "action.report bug": IMsg<string>;
  "bucket.detailslabel": IMsg<string>;
  "bucket.transfer.help": IMsg<string>;
  "bucketactivity.help": IMsg<string>;
  "buckethead.in": IMsg<string>;
  "bucketinout.help": IMsg<string>;
  "bucketrain.help": IMsg<string>;
  "buckettype.deposit": IMsg<string>;
  "buckettype.deposit-date": IMsg<string>;
  "buckettype.goal-date": IMsg<string>;
  "buckettype.goal-deposit": IMsg<string>;
  "buckettype.plain": IMsg<string>;
  "budget-file-type-name": IMsg<string>;
  "daterange.all": IMsg<string>;
  "daterange.from2monthsago": IMsg<string>;
  "daterange.from3monthsago": IMsg<string>;
  "daterange.fromlastmonth": IMsg<string>;
  "daterange.thismonth": IMsg<string>;
  "default account name": IMsg<string>;
  "default new bucket name": IMsg<string>;
  "default new group name": IMsg<string>;
  "edit.mapping": IMsg<(onClick:any)=>string|JSX.Element>;
  "enter-license-prompt": IMsg<string>;
  "error-detail": IMsg<string>;
  "export.why": IMsg<string>;
  "getting-started-link": IMsg<(clickhandler:any)=>string|JSX.Element>;
  "in the bank": IMsg<string>;
  "match-count": IMsg<(current_match:number,total_matches:number)=>string|JSX.Element>;
  "misc group name": IMsg<string>;
  "money-balance-as-of": IMsg<(amount:any,date:any)=>string|JSX.Element>;
  "months gain/loss label": IMsg<(gain:any)=>string|JSX.Element>;
  "more": IMsg<string>;
  "nag-message": IMsg<()=>string|JSX.Element>;
  "navigatestep": IMsg<(url:any)=>string|JSX.Element>;
  "net-transfers.help": IMsg<string>;
  "noin.income": IMsg<string>;
  "notify-downloaded-file": IMsg<(filename:any)=>string|JSX.Element>;
  "noun.transfer": IMsg<string>;
  "off": IMsg<string>;
  "on": IMsg<string>;
  "press Escape to close": IMsg<string>;
  "rain.help.neg": IMsg<(abs_amount:any)=>string|JSX.Element>;
  "rain.help.pos": IMsg<(abs_amount:any)=>string|JSX.Element>;
  "simplefin-connect-intro": IMsg<string>;
  "simplefin-get-token": IMsg<(mklink:any)=>string|JSX.Element>;
  "simplefin-paste": IMsg<string>;
  "single-account Closed": IMsg<string>;
  "single-bucket Kicked": IMsg<string>;
  "some day...": IMsg<string>;
  "sync-symbol help": IMsg<string>;
  "sync.toast.syncing": IMsg<(start:any,end:any)=>string|JSX.Element>;
  "toast.updated-trans": IMsg<(count:any)=>string|JSX.Element>;
  "transfer-from-account": IMsg<(dropdown:any)=>string|JSX.Element>;
  "transfer-to-account": IMsg<(dropdown:any)=>string|JSX.Element>;
  "version-available": IMsg<(newv:string)=>string|JSX.Element>;
}

