// Auto-generated file

import { IMsg, IMessageSet } from '@iffycan/i18n'
export interface IMessages extends IMessageSet {
  "\n        Though filling out this form is preferrable, you can also email bugs@budgetwithbuckets.com\n      ": IMsg<string>;
  "(Blank)": IMsg<string>;
  "(Drop files or click)": IMsg<string>;
  "(If you want a response)": IMsg<string>;
  "(easiest)": IMsg<string>;
  "(optional)": IMsg<string>;
  "/mo": IMsg<string>;
  "A sync is already in progress": IMsg<string>;
  "About Buckets": IMsg<string>;
  "Accept EULA": IMsg<string>;
  "Account": IMsg<string>;
  "Account Transactions": IMsg<string>;
  "Account and transactions deleted": IMsg<string>;
  "Account closed": IMsg<string>;
  "Account deleted completely": IMsg<string>;
  "Account mapping": IMsg<string>;
  "Accounts": IMsg<string>;
  "Accounts in side bar": IMsg<string>;
  "Action": IMsg<string>;
  "Actions": IMsg<string>;
  "Activity": IMsg<string>;
  "Actual Size": IMsg<string>;
  "Advanced settings": IMsg<string>;
  "Agreements": IMsg<string>;
  "All Files": IMsg<string>;
  "Allow new connections": IMsg<string>;
  "Amazon.com Reconciliation": IMsg<string>;
  "Amount": IMsg<string>;
  "Amount of money over-allocated in buckets.": IMsg<string>;
  "Analysis": IMsg<string>;
  "Animation": IMsg<string>;
  "Any other monthly bills you have?": IMsg<string>;
  "App Settings": IMsg<string>;
  "As of": IMsg<string>;
  "Assets": IMsg<string>;
  "Attached files are too large.": IMsg<string>;
  "Authenticated": IMsg<string>;
  "Authenticating": IMsg<string>;
  "Authentication": IMsg<string>;
  "Automatic": IMsg<string>;
  "Available version": IMsg<string>;
  "Avenue available": IMsg<string>;
  "Avenue closed": IMsg<string>;
  "Avenue opened": IMsg<string>;
  "Avenue type": IMsg<string>;
  "Avenue unavailable": IMsg<string>;
  "Avenues": IMsg<string>;
  "Avenues are what you use to connect your devices together so you can send your budget from one device to another.": IMsg<string>;
  "Average": IMsg<string>;
  "Avg:": IMsg<string>;
  "Babysitting": IMsg<string>;
  "Backup file": IMsg<string>;
  "Backup folder": IMsg<string>;
  "Backups": IMsg<string>;
  "Backups enabled": IMsg<string>;
  "Balance": IMsg<string>;
  "Bank macro": IMsg<string>;
  "Basic settings": IMsg<string>;
  "Birthdays": IMsg<string>;
  "Break Import Links": IMsg<string>;
  "Bring All to Front": IMsg<string>;
  "Bucket": IMsg<string>;
  "Bucket Transaction ID": IMsg<string>;
  "Bucket Transactions": IMsg<string>;
  "Bucket amount": IMsg<string>;
  "Bucket deleted completely": IMsg<string>;
  "Bucket group": IMsg<string>;
  "Bucket transaction": IMsg<string>;
  "Bucket type:": IMsg<string>;
  "Buckets": IMsg<string>;
  "Buckets Budget Filename": IMsg<string>;
  "Buckets License": IMsg<string>;
  "Buckets has crashed.  Please restart after submitting a bug report.": IMsg<string>;
  "Budget": IMsg<string>;
  "Budget Specific Settings": IMsg<string>;
  "Budget file": IMsg<string>;
  "Budget files are too different to merge": IMsg<string>;
  "Budget password:": IMsg<string>;
  "Budget-specific number format": IMsg<string>;
  "Budgeted": IMsg<string>;
  "Cable TV": IMsg<string>;
  "Calculator": IMsg<string>;
  "Can't merge budgets of different versions": IMsg<string>;
  "Cancel": IMsg<string>;
  "Cancel Import": IMsg<string>;
  "Cancel Merge": IMsg<string>;
  "Cancel merge": IMsg<string>;
  "Cancel sync": IMsg<string>;
  "Car Insurance": IMsg<string>;
  "Car Maintenance": IMsg<string>;
  "Car Payment": IMsg<string>;
  "Categories": IMsg<string>;
  "Categorization": IMsg<string>;
  "Categorize": IMsg<string>;
  "Category": IMsg<string>;
  "Change": IMsg<string>;
  "Change Account Type": IMsg<string>;
  "Charity": IMsg<string>;
  "Chat with Matt": IMsg<string>;
  "Chat...": IMsg<string>;
  "Check For Updates...": IMsg<string>;
  "Check for Updates": IMsg<string>;
  "Check for updates": IMsg<string>;
  "Checking for updates...": IMsg<string>;
  "Choose": IMsg<string>;
  "Choose a file ending in either .ynab4 or .ymeta": IMsg<string>;
  "Choose save location": IMsg<string>;
  "Choose which of the files on this device you want to make available to your other devices.": IMsg<string>;
  "Choose...": IMsg<string>;
  "Cleared": IMsg<string>;
  "Cleared balance": IMsg<string>;
  "Close Account": IMsg<string>;
  "Close Window": IMsg<string>;
  "Close account": IMsg<string>;
  "Closed": IMsg<string>;
  "Clothing": IMsg<string>;
  "Confirm password:": IMsg<string>;
  "Conflicts": IMsg<string>;
  "Connect": IMsg<string>;
  "Connect to bank": IMsg<string>;
  "Connected": IMsg<string>;
  "Connecting...": IMsg<string>;
  "Connection corrupted. Please delete and re-create.": IMsg<string>;
  "Connection saved!": IMsg<string>;
  "Copy": IMsg<string>;
  "Count": IMsg<string>;
  "Create Account": IMsg<string>;
  "Create Backup": IMsg<string>;
  "Create Backup and Start Over": IMsg<string>;
  "Create Macro": IMsg<string>;
  "Create Template": IMsg<string>;
  "Create Transaction": IMsg<string>;
  "Create budget password:": IMsg<string>;
  "Create macro": IMsg<string>;
  "Create new account": IMsg<string>;
  "Create or manage account": IMsg<string>;
  "Currency symbols": IMsg<string>;
  "Current version": IMsg<string>;
  "Custom": IMsg<string>;
  "Cut": IMsg<string>;
  "Dark": IMsg<string>;
  "Data": IMsg<string>;
  "Date Posted": IMsg<string>;
  "Date format": IMsg<string>;
  "Date range": IMsg<string>;
  "Debt": IMsg<string>;
  "Debugger": IMsg<string>;
  "Debugging": IMsg<string>;
  "Decimal delimiter": IMsg<string>;
  "Default": IMsg<string>;
  "Default number format": IMsg<string>;
  "Delete": IMsg<string>;
  "Delete Account": IMsg<string>;
  "Delete Connection": IMsg<string>;
  "Delete Group": IMsg<string>;
  "Delete Macro": IMsg<string>;
  "Delete Transactions": IMsg<string>;
  "Delete Unknown Account": IMsg<string>;
  "Delete all": IMsg<string>;
  "Deleted": IMsg<string>;
  "Delimiter": IMsg<string>;
  "Description": IMsg<string>;
  "Details": IMsg<string>;
  "Device": IMsg<string>;
  "Device ID": IMsg<string>;
  "Diapers": IMsg<string>;
  "Disable Macro": IMsg<string>;
  "Disconnected": IMsg<string>;
  "Do both devices show the same pairing codes?": IMsg<string>;
  "Done": IMsg<string>;
  "Download Update": IMsg<string>;
  "Downloading update...": IMsg<string>;
  "Duplicate Window": IMsg<string>;
  "Duplicate of existing transaction": IMsg<string>;
  "EULA accepted": IMsg<string>;
  "EULA not accepted": IMsg<string>;
  "EXPERIMENTAL Buckets Macro Maker": IMsg<string>;
  "Eating out": IMsg<string>;
  "Edit": IMsg<string>;
  "Electricity": IMsg<string>;
  "Enable Macro": IMsg<string>;
  "Enabled": IMsg<string>;
  "Encryption": IMsg<string>;
  "Encryption keys": IMsg<string>;
  "Ending Balance": IMsg<string>;
  "Ending amount:": IMsg<string>;
  "Ending balance": IMsg<string>;
  "Enter License...": IMsg<string>;
  "Error": IMsg<string>;
  "Error decrypting recording": IMsg<string>;
  "Error during import": IMsg<string>;
  "Error during merge": IMsg<string>;
  "Error fetching data": IMsg<string>;
  "Error importing": IMsg<string>;
  "Error parsing response": IMsg<string>;
  "Error restoring from backup": IMsg<string>;
  "Error running macro": IMsg<string>;
  "Error running recording": IMsg<string>;
  "Error running sync": IMsg<string>;
  "Error updating transaction": IMsg<string>;
  "Existing version": IMsg<string>;
  "Expenses": IMsg<string>;
  "Export": IMsg<string>;
  "Failed": IMsg<string>;
  "Faint cents": IMsg<string>;
  "File": IMsg<string>;
  "File access error": IMsg<string>;
  "File does not exist:": IMsg<string>;
  "File import mapping": IMsg<string>;
  "File saved: ": IMsg<string>;
  "Files available to sync": IMsg<string>;
  "Filter": IMsg<string>;
  "Find Next": IMsg<string>;
  "Find Previous": IMsg<string>;
  "Find on page": IMsg<string>;
  "Find...": IMsg<string>;
  "Finish merge": IMsg<string>;
  "Folder": IMsg<string>;
  "For Older Budgets": IMsg<string>;
  "Forbidden": IMsg<string>;
  "Force Reload": IMsg<string>;
  "From": IMsg<string>;
  "Fuel": IMsg<string>;
  "Full version": IMsg<string>;
  "Gain/Loss": IMsg<string>;
  "General": IMsg<string>;
  "Getting Started...": IMsg<string>;
  "Go To...": IMsg<string>;
  "Goal completion:": IMsg<string>;
  "Goal:": IMsg<string>;
  "Goal: 0": IMsg<string>;
  "Groceries": IMsg<string>;
  "Guide": IMsg<string>;
  "Health Insurance": IMsg<string>;
  "Hello!  Thanks for trying out Buckets.": IMsg<string>;
  "Help": IMsg<string>;
  "Hide Buckets": IMsg<string>;
  "Hide Others": IMsg<string>;
  "Hide debug info": IMsg<string>;
  "Holidays": IMsg<string>;
  "Host": IMsg<string>;
  "Household goods": IMsg<string>;
  "ID": IMsg<string>;
  "If Net is 0, the bucket transactions will be marked as transfers rather than as income or expenses.": IMsg<string>;
  "Ignore": IMsg<string>;
  "Ignore Account": IMsg<string>;
  "Import": IMsg<string>;
  "Import .zip file": IMsg<string>;
  "Import From Web YNAB...": IMsg<string>;
  "Import From YNAB4...": IMsg<string>;
  "Import Transactions": IMsg<string>;
  "Import Transactions...": IMsg<string>;
  "Import all Amazon Reports": IMsg<string>;
  "Import complete!": IMsg<string>;
  "Import file": IMsg<string>;
  "Import from Web YNAB": IMsg<string>;
  "Import from YNAB4": IMsg<string>;
  "Import links broken": IMsg<string>;
  "In": IMsg<string>;
  "In/Out": IMsg<string>;
  "Include log file": IMsg<string>;
  "Income": IMsg<string>;
  "Income/Expense": IMsg<string>;
  "Incoming budget file": IMsg<string>;
  "Incoming version": IMsg<string>;
  "Install and Relaunch Buckets": IMsg<string>;
  "Internet": IMsg<string>;
  "Invalid categorization.  Categories not set.": IMsg<string>;
  "Invalid date": IMsg<string>;
  "Invalid license": IMsg<string>;
  "Invalid password": IMsg<string>;
  "Invalid transactions preventing import": IMsg<string>;
  "It says:": IMsg<string>;
  "It should say:": IMsg<string>;
  "Keep account transactions": IMsg<string>;
  "Keep accounts": IMsg<string>;
  "Keep bucket transactions": IMsg<string>;
  "Keep buckets": IMsg<string>;
  "Kick Bucket": IMsg<string>;
  "Kick the bucket": IMsg<string>;
  "Kicked": IMsg<string>;
  "Language": IMsg<string>;
  "Last sync": IMsg<string>;
  "Last updated": IMsg<string>;
  "Last used": IMsg<string>;
  "Later": IMsg<string>;
  "Learn More": IMsg<string>;
  "License": IMsg<string>;
  "License status": IMsg<string>;
  "Life Insurance": IMsg<string>;
  "Light": IMsg<string>;
  "Limit": IMsg<string>;
  "Limit:": IMsg<string>;
  "Link Account": IMsg<string>;
  "Local file": IMsg<string>;
  "Local files": IMsg<string>;
  "Local network client": IMsg<string>;
  "Local network server": IMsg<string>;
  "Macros": IMsg<string>;
  "Make Transfer": IMsg<string>;
  "Make it rain!": IMsg<string>;
  "Make it so": IMsg<string>;
  "Mark Cleared": IMsg<string>;
  "Mark Not Cleared": IMsg<string>;
  "Mass Update": IMsg<string>;
  "Medical": IMsg<string>;
  "Memo": IMsg<string>;
  "Memos To Payees": IMsg<string>;
  "Merge": IMsg<string>;
  "Merge Budgets": IMsg<string>;
  "Merge Payees": IMsg<string>;
  "Merge already in progress": IMsg<string>;
  "Merge complete": IMsg<string>;
  "Merge failed": IMsg<string>;
  "Minimize": IMsg<string>;
  "Misc": IMsg<string>;
  "Month to Month": IMsg<string>;
  "Monthly": IMsg<string>;
  "Monthly deposit:": IMsg<string>;
  "Months": IMsg<string>;
  "Move Bucket": IMsg<string>;
  "Move Group": IMsg<string>;
  "Move all transaction memos to blank payee field": IMsg<string>;
  "NO": IMsg<string>;
  "Name": IMsg<string>;
  "Natural gas/propane/oil": IMsg<string>;
  "Need ideas for getting started?": IMsg<string>;
  "Needs": IMsg<string>;
  "Negate": IMsg<string>;
  "Negative": IMsg<string>;
  "Net": IMsg<string>;
  "Net Transfers": IMsg<string>;
  "Net Wealth": IMsg<string>;
  "Net change": IMsg<string>;
  "New Bucket": IMsg<string>;
  "New Budget...": IMsg<string>;
  "New Group": IMsg<string>;
  "New account": IMsg<string>;
  "New avenue": IMsg<string>;
  "New bucket": IMsg<string>;
  "New car": IMsg<string>;
  "New computer": IMsg<string>;
  "New phone": IMsg<string>;
  "New roof": IMsg<string>;
  "New transaction": IMsg<string>;
  "New value": IMsg<string>;
  "No": IMsg<string>;
  "No conflicts": IMsg<string>;
  "No matches found": IMsg<string>;
  "No name": IMsg<string>;
  "No orders imported": IMsg<string>;
  "No refunds imported": IMsg<string>;
  "No, don't connect": IMsg<string>;
  "Normal": IMsg<string>;
  "Not Transfer": IMsg<string>;
  "Not running": IMsg<string>;
  "Not yet cleared": IMsg<string>;
  "Note": IMsg<string>;
  "Nothing found matching:": IMsg<string>;
  "Number format": IMsg<string>;
  "OBJ.account_id": IMsg<string>;
  "OBJ.amount": IMsg<string>;
  "OBJ.created": IMsg<string>;
  "OBJ.id": IMsg<string>;
  "OBJ.last_used": IMsg<string>;
  "OBJ.memo": IMsg<string>;
  "OBJ.notes": IMsg<string>;
  "OBJ.payee": IMsg<string>;
  "OBJ.posted": IMsg<string>;
  "OFF": IMsg<string>;
  "OK": IMsg<string>;
  "ON": IMsg<string>;
  "Off Budget Accounts": IMsg<string>;
  "Off budget": IMsg<string>;
  "On": IMsg<string>;
  "Open Anyway": IMsg<string>;
  "Open Buckets Budget": IMsg<string>;
  "Open Budget...": IMsg<string>;
  "Open Recent...": IMsg<string>;
  "Open Transaction File": IMsg<string>;
  "Open Web YNAB Zip File": IMsg<string>;
  "Open YNAB4 File": IMsg<string>;
  "Opening balance": IMsg<string>;
  "Optional message:": IMsg<string>;
  "Optionally request an Amazon Refunds report": IMsg<string>;
  "Or click to download the new version manually.": IMsg<string>;
  "Order": IMsg<string>;
  "Orders": IMsg<string>;
  "Other devices have made the following files available. Choose where you would like to save them on this device.": IMsg<string>;
  "Out": IMsg<string>;
  "Overwrite budget from backup": IMsg<string>;
  "Pairing code": IMsg<string>;
  "Password": IMsg<string>;
  "Password not yet set": IMsg<string>;
  "Password reset": IMsg<string>;
  "Passwords did not match": IMsg<string>;
  "Paste": IMsg<string>;
  "Paste and Match Style": IMsg<string>;
  "Paused": IMsg<string>;
  "Payee": IMsg<string>;
  "Payees": IMsg<string>;
  "Pending merges": IMsg<string>;
  "Pending...": IMsg<string>;
  "Permanently delete account and transactions": IMsg<string>;
  "Personal Loan Payment": IMsg<string>;
  "Phone": IMsg<string>;
  "Playing": IMsg<string>;
  "Please enter your Buckets License below.": IMsg<string>;
  "Port": IMsg<string>;
  "Possible Duplicates": IMsg<string>;
  "Posted": IMsg<string>;
  "Preferences...": IMsg<string>;
  "Preparation": IMsg<string>;
  "Preview": IMsg<string>;
  "Print...": IMsg<string>;
  "Prompt": IMsg<string>;
  "Purchase": IMsg<string>;
  "Purchase Full Version...": IMsg<string>;
  "Purchase license": IMsg<string>;
  "Quit Buckets": IMsg<string>;
  "Rain": IMsg<string>;
  "Rain left": IMsg<string>;
  "Recently used": IMsg<string>;
  "Record change as transaction": IMsg<string>;
  "Recording": IMsg<string>;
  "Recurring Expenses": IMsg<string>;
  "Redo": IMsg<string>;
  "Refunds": IMsg<string>;
  "Regenerate": IMsg<string>;
  "Registered to": IMsg<string>;
  "Relay client": IMsg<string>;
  "Relay server": IMsg<string>;
  "Reload": IMsg<string>;
  "Remote device": IMsg<string>;
  "Remote devices": IMsg<string>;
  "Remote file": IMsg<string>;
  "Remove Categorization": IMsg<string>;
  "Rent/Mortgage": IMsg<string>;
  "Reopen": IMsg<string>;
  "Reopen Account": IMsg<string>;
  "Report Bug": IMsg<string>;
  "Report Bug...": IMsg<string>;
  "Report Translation Error...": IMsg<string>;
  "Request an Amazon Items report": IMsg<string>;
  "Request an Amazon Orders report": IMsg<string>;
  "Required deposit:": IMsg<string>;
  "Reset Password": IMsg<string>;
  "Reset bank macro password": IMsg<string>;
  "Restart Buckets": IMsg<string>;
  "Restart Buckets for changes to take effect.": IMsg<string>;
  "Restore from backup": IMsg<string>;
  "Restored budget from backup": IMsg<string>;
  "Reverse": IMsg<string>;
  "Run": IMsg<string>;
  "Running": IMsg<string>;
  "Running...": IMsg<string>;
  "SQL Query": IMsg<string>;
  "Save": IMsg<string>;
  "Screenshots:": IMsg<string>;
  "Search": IMsg<string>;
  "Search categories": IMsg<string>;
  "Search for Amazon transactions:": IMsg<string>;
  "Search...": IMsg<string>;
  "Search:": IMsg<string>;
  "Searching...": IMsg<string>;
  "Select All": IMsg<string>;
  "Self debt": IMsg<string>;
  "Send Report": IMsg<string>;
  "Services": IMsg<string>;
  "Set Mapping": IMsg<string>;
  "Setting": IMsg<string>;
  "Settings": IMsg<string>;
  "Share with": IMsg<string>;
  "Shared folder": IMsg<string>;
  "Sharing": IMsg<string>;
  "Sharing key": IMsg<string>;
  "Show All": IMsg<string>;
  "Show Budget File...": IMsg<string>;
  "Show Log Files...": IMsg<string>;
  "Show debug info": IMsg<string>;
  "Show folder": IMsg<string>;
  "Show full changelog": IMsg<string>;
  "Sign": IMsg<string>;
  "Sign in to the YNAB website, click My Budget then Export Budget.": IMsg<string>;
  "SimpleFIN Connections": IMsg<string>;
  "SimpleFIN connection": IMsg<string>;
  "Since some buckets have negative balances, this payment balance may not be what you actually have available for a payment.": IMsg<string>;
  "Skip This Version": IMsg<string>;
  "Skip invalid": IMsg<string>;
  "Speech": IMsg<string>;
  "Spending Money": IMsg<string>;
  "Start Merge": IMsg<string>;
  "Start Over": IMsg<string>;
  "Start Speaking": IMsg<string>;
  "Start with a template": IMsg<string>;
  "Status": IMsg<string>;
  "Step took too long": IMsg<string>;
  "Stop Speaking": IMsg<string>;
  "Stopped": IMsg<string>;
  "Student Loan Payment": IMsg<string>;
  "Success!": IMsg<string>;
  "Successfully imported Amazon Items report": IMsg<string>;
  "Successfully imported Amazon Orders report": IMsg<string>;
  "Successfully imported Amazon Refunds report": IMsg<string>;
  "Suggested value": IMsg<string>;
  "Swap NAME and MEMO": IMsg<string>;
  "Sync": IMsg<string>;
  "Sync complete": IMsg<string>;
  "Sync has not yet been set up.": IMsg<string>;
  "Synced balance": IMsg<string>;
  "Syncing...": IMsg<string>;
  "System default": IMsg<string>;
  "Target date:": IMsg<string>;
  "Test Toast": IMsg<string>;
  "Theme": IMsg<string>;
  "There are unresolved conflicts": IMsg<string>;
  "There has been an error.": IMsg<string>;
  "There was an error.  Maybe try again?": IMsg<string>;
  "These devices can talk to each other": IMsg<string>;
  "This budget was upgraded for a newer version of Buckets.  Using it with this older version may not work.": IMsg<string>;
  "This device's name": IMsg<string>;
  "This is a special group for all the buckets without a group.": IMsg<string>;
  "This tool will delete data to make it easy to start over with your budget.": IMsg<string>;
  "This will break all existing bank macros": IMsg<string>;
  "Thousands separator": IMsg<string>;
  "To": IMsg<string>;
  "To use Buckets, you must accept the End User License Agreement (EULA).": IMsg<string>;
  "Toggle Developer Tools": IMsg<string>;
  "Toggle Full Screen": IMsg<string>;
  "Tools": IMsg<string>;
  "Total": IMsg<string>;
  "Total amount your buckets want each month.": IMsg<string>;
  "Transaction": IMsg<string>;
  "Transaction ID": IMsg<string>;
  "Transactions": IMsg<string>;
  "Transactions to review": IMsg<string>;
  "Transfer": IMsg<string>;
  "Transferred": IMsg<string>;
  "Trial Version": IMsg<string>;
  "Trial version": IMsg<string>;
  "Try the Amazon transactions page instead of using the reports below.": IMsg<string>;
  "Tuition": IMsg<string>;
  "Type a date format...": IMsg<string>;
  "Un-ignore Account": IMsg<string>;
  "Un-kick": IMsg<string>;
  "Un-kick Bucket": IMsg<string>;
  "Unable to claim access token": IMsg<string>;
  "Unable to open the file:": IMsg<string>;
  "Unattended merge not possible": IMsg<string>;
  "Unavailable": IMsg<string>;
  "Uncategorized": IMsg<string>;
  "Uncaught Error": IMsg<string>;
  "Uncleared": IMsg<string>;
  "Undo": IMsg<string>;
  "Unexpected sync error": IMsg<string>;
  "Unknown account": IMsg<string>;
  "Unknown category": IMsg<string>;
  "Unlinked Accounts": IMsg<string>;
  "Unregistered Version": IMsg<string>;
  "Update": IMsg<string>;
  "Update Account Balance": IMsg<string>;
  "Update Account Name": IMsg<string>;
  "Update Bucket Name": IMsg<string>;
  "Update Bucket Type": IMsg<string>;
  "Update Color": IMsg<string>;
  "Update Currency Symbol": IMsg<string>;
  "Update Goal": IMsg<string>;
  "Update Group Name": IMsg<string>;
  "Update Macro Name": IMsg<string>;
  "Update Monthly Deposit": IMsg<string>;
  "Update Name": IMsg<string>;
  "Update Note": IMsg<string>;
  "Update Number Format": IMsg<string>;
  "Update Payee": IMsg<string>;
  "Update Payees": IMsg<string>;
  "Update Target Date": IMsg<string>;
  "Update Transaction": IMsg<string>;
  "Update account balance": IMsg<string>;
  "Update balance": IMsg<string>;
  "Update complete": IMsg<string>;
  "Update downloaded.": IMsg<string>;
  "Update failed": IMsg<string>;
  "Update opening balance": IMsg<string>;
  "Updated": IMsg<string>;
  "Updates": IMsg<string>;
  "Updating...": IMsg<string>;
  "Used in future": IMsg<string>;
  "Username": IMsg<string>;
  "Username/Password": IMsg<string>;
  "Using this tool can ruin your budget file.  Make a copy of your budget if you're worried.": IMsg<string>;
  "Vacation ": IMsg<string>;
  "View": IMsg<string>;
  "View EULA": IMsg<string>;
  "Waiting to retry": IMsg<string>;
  "Want": IMsg<string>;
  "Wants": IMsg<string>;
  "Warning: Doing this will use rain you don't have and could steal rain from future months (if available).": IMsg<string>;
  "Water": IMsg<string>;
  "Web YNAB Export": IMsg<string>;
  "When \"On\" this macro will be run during a normal sync.": IMsg<string>;
  "Window": IMsg<string>;
  "YES": IMsg<string>;
  "Year to Year": IMsg<string>;
  "Year's Supply": IMsg<string>;
  "Yearly": IMsg<string>;
  "Years": IMsg<string>;
  "Yes": IMsg<string>;
  "Yes, connect": IMsg<string>;
  "You are running the latest version!": IMsg<string>;
  "You can do math in all number inputs, not just here in the calculator.": IMsg<string>;
  "You don't have any recurring expense buckets yet.": IMsg<string>;
  "You have no closed accounts.": IMsg<string>;
  "You haven't kicked the bucket yet...": IMsg<string>;
  "You must backup to a different file.": IMsg<string>;
  "Your email address:": IMsg<string>;
  "Zoom": IMsg<string>;
  "Zoom In": IMsg<string>;
  "Zoom Out": IMsg<string>;
  "account-in": IMsg<string>;
  "account-net-amount": IMsg<string>;
  "account-out": IMsg<string>;
  "account-type": IMsg<string>;
  "account.balance": IMsg<string>;
  "account.closed": IMsg<string>;
  "account.currency": IMsg<string>;
  "account.import_balance": IMsg<string>;
  "account.kind": IMsg<string>;
  "account.name": IMsg<string>;
  "account.offbudget": IMsg<string>;
  "account.starting_balance": IMsg<string>;
  "account_mapping.account_hash": IMsg<string>;
  "account_transaction.cleared": IMsg<string>;
  "account_transaction.fi_id": IMsg<string>;
  "account_transaction.general_cat": IMsg<string>;
  "accounts.name_placeholder": IMsg<string>;
  "action.New bucket": IMsg<string>;
  "action.New group": IMsg<string>;
  "action.ignore": IMsg<string>;
  "action.link-account": IMsg<string>;
  "action.report bug": IMsg<string>;
  "bank_macro.enabled": IMsg<string>;
  "bank_macro.enc_recording": IMsg<string>;
  "bank_macro.name": IMsg<string>;
  "bank_macro.uuid": IMsg<string>;
  "bucket.balance": IMsg<string>;
  "bucket.color": IMsg<string>;
  "bucket.debt_account_id": IMsg<string>;
  "bucket.deposit": IMsg<string>;
  "bucket.detailslabel": IMsg<string>;
  "bucket.end_date": IMsg<string>;
  "bucket.goal": IMsg<string>;
  "bucket.group_id": IMsg<string>;
  "bucket.kicked": IMsg<string>;
  "bucket.kind": IMsg<string>;
  "bucket.name": IMsg<string>;
  "bucket.ranking": IMsg<string>;
  "bucket.transfer.help": IMsg<string>;
  "bucket_group.name": IMsg<string>;
  "bucket_group.ranking": IMsg<string>;
  "bucket_transaction.account_trans_id": IMsg<string>;
  "bucket_transaction.bucket_id": IMsg<string>;
  "bucket_transaction.linked_trans_id": IMsg<string>;
  "bucket_transaction.transfer": IMsg<string>;
  "buckethead.activity": IMsg<string>;
  "buckethead.fill": IMsg<string>;
  "bucketinout.help": IMsg<string>;
  "bucketrain.help": IMsg<string>;
  "buckettype.deposit": IMsg<string>;
  "buckettype.deposit-date": IMsg<string>;
  "buckettype.goal-date": IMsg<string>;
  "buckettype.goal-deposit": IMsg<string>;
  "buckettype.plain": IMsg<string>;
  "budget-file-type-name": IMsg<string>;
  "change_log.action": IMsg<string>;
  "change_log.obj": IMsg<string>;
  "change_log.obj_id": IMsg<string>;
  "daterange.all": IMsg<string>;
  "debt-bucket-explanation": IMsg<string>;
  "debt-payment-bucket-name": IMsg<(account_name:string)=>string|JSX.Element>;
  "default account name": IMsg<string>;
  "default new bucket name": IMsg<string>;
  "default new group name": IMsg<string>;
  "err": IMsg<string>;
  "error-detail": IMsg<string>;
  "file_import_mapping.mapping_json": IMsg<string>;
  "getting-started-link": IMsg<(clickhandler:any)=>string|JSX.Element>;
  "go-to-next-month": IMsg<string>;
  "go-to-next-year": IMsg<string>;
  "go-to-prev-month": IMsg<string>;
  "go-to-prev-year": IMsg<string>;
  "go-to-this-month": IMsg<string>;
  "import-verb": IMsg<string>;
  "in the bank": IMsg<string>;
  "misc group name": IMsg<string>;
  "money-balance-as-of": IMsg<(amount:any,date:any)=>string|JSX.Element>;
  "months gain/loss label": IMsg<(gain:any)=>string|JSX.Element>;
  "more": IMsg<string>;
  "nag-message": IMsg<()=>string|JSX.Element>;
  "navigatestep": IMsg<(url:any)=>string|JSX.Element>;
  "net-transfers.help": IMsg<string>;
  "no name": IMsg<string>;
  "noin.income": IMsg<string>;
  "notify-downloaded-file": IMsg<(filename:any)=>string|JSX.Element>;
  "noun.debt": IMsg<string>;
  "noun.transfer": IMsg<string>;
  "off": IMsg<string>;
  "on": IMsg<string>;
  "press Escape to close": IMsg<string>;
  "rain.help.neg": IMsg<(abs_amount:any)=>string|JSX.Element>;
  "rain.help.pos": IMsg<(abs_amount:any)=>string|JSX.Element>;
  "sample-size": IMsg<(count:number,total:number)=>string|JSX.Element>;
  "settings.key": IMsg<string>;
  "settings.value": IMsg<string>;
  "shipment-number": IMsg<(number:number)=>string|JSX.Element>;
  "simplefin-connect-intro": IMsg<string>;
  "simplefin-get-token": IMsg<(mklink:any)=>string|JSX.Element>;
  "simplefin-paste": IMsg<string>;
  "simplefin_connection.access_token": IMsg<string>;
  "single-account Closed": IMsg<string>;
  "single-bucket Kicked": IMsg<string>;
  "some day...": IMsg<string>;
  "sync-symbol help": IMsg<string>;
  "sync.toast.syncing": IMsg<(start:string,end:string)=>string|JSX.Element>;
  "tab": IMsg<string>;
  "this_device.name": IMsg<string>;
  "toast.updated-trans": IMsg<(count:any)=>string|JSX.Element>;
  "trans-created-outofview": IMsg<(month:string)=>string|JSX.Element>;
  "transfer-from-account": IMsg<(dropdown:any)=>string|JSX.Element>;
  "transfer-to-account": IMsg<(dropdown:any)=>string|JSX.Element>;
  "unknown_account.account_hash": IMsg<string>;
  "unknown_account.description": IMsg<string>;
  "unknown_account.ignore": IMsg<string>;
  "use-delimiter": IMsg<(delimiter:string)=>string|JSX.Element>;
  "verb-open": IMsg<string>;
}

